version: '3.8'

services:
  mongodb-test:
    image: mongo:latest
    container_name: test_mongodb
    ports:
      - "27015:27017"
    environment:
      MONGO_INITDB_DATABASE: test_stock_db
  protoc:
    build:
      context: ./tools/protoc
    volumes:
      - ./src/proto:/app/src/proto
      - ./tools/protoc:/app/tools/protoc
    working_dir: /app
    command: [ "/app/tools/protoc/gen-protoc.sh" ]

networks:
  default:
    name: python-proto-net
