version: '3.8'

services:
  protoc:
    build:
      context: ./tools/protoc
    volumes:
      - ./src/proto:/app/src/proto
      - ./tools/protoc:/app/tools/protoc
    working_dir: /app
    command: ["/app/tools/protoc/gen-protoc.sh"]

networks:
  default:
    name: python-proto-net