name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb-test:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install --system -r pyproject.toml
          uv pip install --system pytest flake8

      - name: Run linter (flake8)
        run: |
          flake8 src/ --max-line-length=88 --extend-ignore=E203

      - name: Generate protobuf files
        run: make generate

      - name: Run tests
        run: make test

      - name: Cleanup
        if: always()
        run: |
          docker-compose down -v
          rm -rf __pycache__ tests/__pycache__